//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemcliT_WCF.App_Data {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConnectionSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConnectionSources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemcliT_WCF.App_Data.ConnectionSources", typeof(ConnectionSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Source=10.80.3.139\SQLINSTNOCORE;Initial Catalog=NABISD;Persist Security Info=True;User ID=Nabmin;Password=$jcloop;.
        /// </summary>
        public static string Nabis {
            get {
                return ResourceManager.GetString("Nabis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Source=10.80.3.146\sqlinstprepro;Initial Catalog=NABISP;Persist Security Info=True;User ID=NabminP;Password=pook;.
        /// </summary>
        public static string NabisDeveloper {
            get {
                return ResourceManager.GetString("NabisDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Source=10.80.3.146\sqlinstprepro;Initial Catalog=NABISD;Persist Security Info=True;User ID=Nabmin;Password=$jcloop;.
        /// </summary>
        public static string NabisTest {
            get {
                return ResourceManager.GetString("NabisTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SERVER=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.80.1.20)(PORT=3347))(CONNECT_DATA=(SERVICE_NAME=SCEL)));uid=usr_stp_et;pwd=Stp_TCOL_2013.
        /// </summary>
        public static string SCL {
            get {
                return ResourceManager.GetString("SCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEMCLIT2018*.
        /// </summary>
        public static string WsPagosClave {
            get {
                return ResourceManager.GetString("WsPagosClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DENCLIT_2018*.
        /// </summary>
        public static string WsPagosClaveTest {
            get {
                return ResourceManager.GetString("WsPagosClaveTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DEMCLIT.
        /// </summary>
        public static string WsPagosUsuario {
            get {
                return ResourceManager.GetString("WsPagosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DENCLIT_2018.
        /// </summary>
        public static string WsPagosUsuarioTest {
            get {
                return ResourceManager.GetString("WsPagosUsuarioTest", resourceCulture);
            }
        }
    }
}
